### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by mateuskuritza** [EricRubbo/Projeto-1#1]
# Deploy

> O deploy é o processo de colocar sua aplicação disponível na web, podendo ser realizado em diferentes plataformas. Neste caso, como estamos lidando apenas com HTML, CSS e JavaScript, o deploy mais simples (na minha opinião) e também gratuito é utilizando o GitHub Pages. 

[Aqui está um artigo que explica como fazer isso.](https://www.alura.com.br/artigos/como-colocar-projeto-no-ar-com-github-pages?srsltid=AfmBOop69O72SpyxhVeM4ACXrLiqf99gJOirqc4gR9hPRnm2hI_4CeJT)

## Bônus: navegação

Criar mais de uma página e um forma de ir de uma para a outra. Por exemplo: uma home (página aberta por padrão) e outra página com a url "/sobre"

**Comment by EricRubbo** [comment]
Resolvido
