### ISSUE TITLE
Seletores CSS

### ISSUE THREAD

**Issue by mateuskuritza** [EricRubbo/Projeto-1#3]
Tá ficando bem legal o menu lateral, com animação e tudo, parabéns!

### Tentar criar menos classes/ids utilizando seletores do CSS. Por exemplo:

Ao invés de:

```html
<div id="right">
    <div id="add">
        <a href="#"><img src="../pngs/plus.png" alt="adicionar" width="25px" height="25px" id="add"></a>
    </div>
    <a href="#"><img src="../pngs/user.png" alt="Usuário" id="user"></a>
</div>
```

Poderia ser algo como:

```html
<div id="right">
    <div>
        <a href="#"><img src="../pngs/plus.png" alt="adicionar" width="25px" height="25px"></a>
    </div>
    <a href="#"><img src="../pngs/user.png" alt="Usuário"></a>
</div>
```

E no CSS:
```css
#right > a { ... }
#right > div > a { ... }
```

Pode parecer mais complexo mas normalmente se ganha em não espalhar a estilização em mts lugares dificultando a manutenção.

---

### ID com css inline

`<img src="../pngs/plus.png" alt="adicionar" width="25px" height="25px" id="add"> `

O elemento tem um ID e também tem estilização `inline` (width e height). Nesse caso o ideal é deixar tudo na estilização do próprio ID. 

---

### Multiplos elementos com o mesmo ID

Tem mais de um elemento com o ID `add` (tem outros ids repetidos). Se for para existirem elementos com o mesmo identificador nós devemos utilizar as classes, ID's  devem ser únicos na página por conta de algumas funcionalidades do HTML (como formulários), do Javascript (buscar elementos específicos da página) e da própria semântica de código (se eu vejo um input com o `id="name"`, eu entendo que só existe um desse quando for mexer com o JS para pegar esse nome, agora se eu ver com `class="name"`, só de ler isso já vou entender que tem mais de um e devo tomar esse cuidado no JS)

Curiosidade sobre ids e javascript q eu nunca vi ngm usando: se vc acessar essa página, for no console do navegador e digitar "left" (o id de um dos elementos), o elemento vai aparecer no console. O id em um elemento HTML cria uma variável no JS com o mesmo nome.

**Comment by EricRubbo** [comment]
Ajustado!
